# Generated by Django 5.2.7 on 2025-11-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chat_chatro_user_on_c37c83_idx',
            old_name='chat_chat_user_on_d8f117_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_5feac5_idx',
            old_name='chat_messa_room_i_41a71e_idx',
        ),
    ]
