# Generated by Django 5.2.7 on 2025-11-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='matchaction',
            new_name='matches_mat_initiat_10a6e0_idx',
            old_name='matches_ma_initia_0a03b9_idx',
        ),
        migrations.RenameIndex(
            model_name='matchaction',
            new_name='matches_mat_target__71cbb1_idx',
            old_name='matches_ma_target_d97ab0_idx',
        ),
        migrations.RenameIndex(
            model_name='mutualmatch',
            new_name='matches_mut_user_on_2f0232_idx',
            old_name='matches_mu_user_on_8f1a4a_idx',
        ),
    ]
