# Generated by Django 5.2.7 on 2025-11-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_pr_city_491350_idx',
            old_name='profiles_pr_city_7cd829_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_pr_religio_f6b0f5_idx',
            old_name='profiles_pr_religi_25d4b9_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_pr_gender_fc2e15_idx',
            old_name='profiles_pr_gender_759fa7_idx',
        ),
    ]
